### ISSUE TITLE
Changement config.js  

### ISSUE THREAD

**Issue by mathildehg** [etalab/guides#14]
Je m'entraine à faire évoluer config.js du VuePress avec l'ajout du guide datagouv. Une fois que les md de datagouv seront à la racine de datagouv, est-ce que ca ressemblerait à ca ? 

sidebar = {
  '/qualite/': [
    '',
    '0-introduction',
    '1-preparer-le-jeu-de-donnees',
    '2-documenter-les-donnees',
    '3-elements-organisationnels',
  ],
  '/datagouv/': [
    '',
    '0-introduction',
    '1-creer-un-compte-utilisateur',
    '2-creer-ou-rejoindre-une-organisation',
    '3-publier-un-jeu-de-donnees',
    '4-animer-la-communaute-de-reutilisateurs',
  ],
  // add other guides here, like this:
  // '/dummy/': [
  //   '',
  //   'dummy-child',
  //   'dummy-child-dir/dummy-child-dir-child'
  // ]
}

module.exports = {
  title: 'guides.etalab.gouv.fr',
  description: 'Les guides d\'Etalab',
  themeConfig: {
    sidebar: sidebar,
    sidebarDepth: 1,
    logo: '/images/logo-marianne.svg',
    // lastUpdated: 'Dernière mise à jour',
    repo: 'etalab/guides',
    editLinks: true,
    editLinkText: 'Proposer des modifications sur cette page'
  },
  locales: {'/': {lang: 'fr-FR'}},
  dest: 'public',
  head: [
    ['link', { rel: 'icon', href: '/images/favicon.png' }],
  ],
  markdown: {
    toc: { includeLevel: [2, 3, 4, 5] }
  }
}

**Comment by abulte** [comment]
Looks good

**Comment by abulte** [comment]
Si tu fais une PR en changeant le fichier, tu pourras tester les changements direct en cliquant sur les liens `now[bot] deployed to staging`

**Comment by taniki** [comment]
un peu lourdingue. c'est pas le moment où on tweak un peu le thème par défaut pour n'avoir qu'à donner le répertoire à inclure comme entrée ?

**Comment by abulte** [comment]
Why not! Après 8 lignes pour ajouter un guide ça ne me paraît pas insurmontable non plus ;-)

**Comment by abulte** [comment]
Bon c’est malin j’ai envie de le faire maintenant (-:

**Comment by abulte** [comment]
https://github.com/onlydel/vuepress-dir-sidebar/blob/master/lib/vuepress-dir-sidebar.js

https://github.com/ozum/vuepress-bar

**Comment by mathildehg** [comment]
Il va falloir m'expliquer tout ça ! (:

**Comment by abulte** [comment]
@mathildehg TLDR; avec #15, plus besoin de changer le `config.js` pour ajouter un guide 🎉
