### ISSUE TITLE
Local deployment instructions fail

### ISSUE THREAD

**Issue by bzg** [etalab/guides#25]
Hello, I try to clone and to run `yarn install` but was bitten by this:

> 00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

Is it on my side or is there something missing in the instructions?

**Comment by AntoineAugusti** [comment]
I can confirm than the instructions work on macOS.

This [StackOverflow question](https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install) seems to explain how to fix it on Linux. Can you try?

You can also use `npm` instead of `yarn`.

**Comment by bzg** [comment]
Thanks for the fix in the `README.md`, I confirm the new instructions work on my machine, closing now.

**Comment by AntoineAugusti** [comment]
Just to be clear, people should be able to use npm or yarn, whatever they prefer
