### ISSUE TITLE
Ajout d'une licence

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/guides#3]
Il faudrait une licence sur ce dépôt à terme.

Je pense qu'il en faut 2 : une pour le peu de code et l'autre pour le contenu du guide.

D'instinct, je dirais MIT / LO.

Vous avez la même lecture ?
Comment raisonnablement bien spécifier 2 licences différentes dans un même dépôt ?

**Comment by abulte** [comment]
> Il faudrait une licence sur ce dépôt à terme.
> 
> Je pense qu'il en faut 2 : une pour le peu de code et l'autre pour le contenu du guide.
> 
> D'instinct, je dirais MIT / LO.

Oui.

> Vous avez la même lecture ?
> Comment raisonnablement bien spécifier 2 licences différentes dans un même dépôt ?

Pas vraiment :-/ Peut-être package.json pour le code et README.md pour le contenu.

**Comment by AntoineAugusti** [comment]
@bzg, un avis sur les bonnes pratiques pour mettre en évidence la double licence ? J'ai testé quelque chose dans #5.

**Comment by AntoineAugusti** [comment]
@bzg m'a répondu à l'oral qu'il n'y avait pas une bonne pratique claire et que le fait de mentionner ceci dans le README était acceptable pour le moment.

Je clos cette issue.
